### ISSUE TITLE
V19 

### ISSUE THREAD

**Issue by erlicthemad** [AJARProject/AJ_Math#1]
**Is your feature request related to a problem? Please describe.**
I have switched to using 4D v19 and have your systems in my project. Many of my other COmponents I had source code and just rebuilt for Universal Mac support. I see you did not have this or the source. Are you planning on making universal versions of your components?

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by minzirillo** [comment]
Hi,

A new release 2.0.2 is available which is addressing this issue.
